inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
enable_envvars_config=true
install_py_dep_per_model=true
load_models=recs=book-recs.mar
max_response_size=10000000
enable_metrics_api=true
disable_token_authorization=true
